// Decompiled with JetBrains decompiler
// Type: CharReference
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 3FB45F06-6483-4AD8-97CB-A1C42CCDD6C3
// Assembly location: E:\GAME\illusion_AI\PluginDev\反编译阅读\AI_Assembly-CSharp.dll

public class CharReference
{
  public const ulong FbxTypeBone = 1;
  public const ulong FbxTypeBody = 2;
  public const ulong FbxTypeHead = 3;
  public const ulong FbxTypeBase = 8;

  public enum RefObjKey_New
  {
    HeadParent,
    HairParent,
    AP_Hair_Twin_L,
    AP_Hair_Twin_R,
    AP_Hair_pin_L,
    AP_Hair_pin_R,
    AP_Head_Top,
    AP_Head,
    AP_Hitai,
    AP_Face,
    AP_Megane,
    AP_Earring_L,
    AP_Earring_R,
    AP_Nose,
    AP_Mouth,
    AP_Neck,
    AP_Chest_F,
    AP_Chest,
    AP_Tikubi_L,
    AP_Tikubi_R,
    AP_Back,
    AP_Back_L,
    AP_Back_R,
    AP_Waist,
    AP_Waist_F,
    AP_Waist_B,
    AP_Waist_L,
    AP_Waist_R,
    AP_Leg_L,
    AP_Leg_R,
    AP_Knee_L,
    AP_Knee_R,
    AP_Ankle_L,
    AP_Ankle_R,
    AP_Foot_L,
    AP_Foot_R,
    AP_Shoulder_L,
    AP_Shoulder_R,
    AP_Elbo_L,
    AP_Elbo_R,
    AP_Arm_L,
    AP_Arm_R,
    AP_Wrist_L,
    AP_Wrist_R,
    AP_Hand_L,
    AP_Hand_R,
    AP_Index_L,
    AP_Index_R,
    AP_Middle_L,
    AP_Middle_R,
    AP_Ring_L,
    AP_Ring_R,
    AP_Dan,
    AP_Kokan,
    AP_Ana,
  }

  public enum RefObjKey
  {
    HeadParent,
    HairParent,
    AP_Head,
    AP_Megane,
    AP_Earring_L,
    AP_Earring_R,
    AP_Mouth,
    AP_Nose,
    AP_Neck,
    AP_Chest,
    AP_Wrist_L,
    AP_Wrist_R,
    AP_Arm_L,
    AP_Arm_R,
    AP_Index_L,
    AP_Index_R,
    AP_Middle_L,
    AP_Middle_R,
    AP_Ring_L,
    AP_Ring_R,
    AP_Leg_L,
    AP_Leg_R,
    AP_Ankle_L,
    AP_Ankle_R,
    AP_Tikubi_L,
    AP_Tikubi_R,
    AP_Waist,
    AP_Shoulder_L,
    AP_Shoulder_R,
    AP_Hand_L,
    AP_Hand_R,
    AP_Hand_L_NEO,
    H_Kokan,
    H_DanDir,
    S_TongueF,
    S_TongueB,
    S_MNPB,
    S_NIP,
    S_TEARS_01,
    S_TEARS_02,
    S_TEARS_03,
    F_ADJUSTWIDTHSCALE,
    A_ROOTBONE,
  }

  public enum TagObjKey
  {
    ObjHairB,
    ObjHairF,
    ObjHairS,
    ObjHairO,
    ObjHairAcsB,
    ObjHairAcsF,
    ObjHairAcsS,
    ObjHairAcsO,
    ObjSkinFace,
    ObjEyebrow,
    ObjEyeL,
    ObjEyeR,
    ObjEyeHi,
    ObjEyelashes,
    ObjBeard,
    ObjEyeW,
    ObjNail,
    ObjNip,
    ObjUnderHair,
    ObjSkinBody,
    ObjCTop,
    ObjCBot,
    ObjBra,
    ObjShorts,
    ObjGloves,
    ObjPanst,
    ObjSocks,
    ObjShoes,
    ObjSwim,
    ObjSTop,
    ObjSBot,
    ObjASlot01,
    ObjASlot02,
    ObjASlot03,
    ObjASlot04,
    ObjASlot05,
    ObjASlot06,
    ObjASlot07,
    ObjASlot08,
    ObjASlot09,
    ObjASlot10,
  }
}
